import { AppraisalDossier, RoadmapStep } from '../types';
import { getAccessToken } from './firebase';

export interface SpreadsheetExportResult {
  spreadsheetId: string;
  spreadsheetUrl: string;
  title: string;
  rowCount: number;
}

export interface GoogleTaskItem {
  id: string;
  title: string;
  notes?: string;
  status: 'needsAction' | 'completed';
  due?: string;
  completed?: string;
  updated?: string;
}

export interface GoogleTaskList {
  id: string;
  title: string;
  updated: string;
}

// ----------------------------------------------------
// GOOGLE SHEETS SERVICE
// ----------------------------------------------------

export async function exportInventoryToGoogleSheet(
  items: AppraisalDossier[],
  customTitle?: string
): Promise<SpreadsheetExportResult> {
  const token = await getAccessToken();
  if (!token) {
    throw new Error('Google authentication required. Please sign in with Google to export to Sheets.');
  }

  const title = customTitle || `ShutterBuck Inventory Ledger (${new Date().toLocaleDateString()})`;

  // 1. Create a new Spreadsheet
  const createRes = await fetch('https://sheets.googleapis.com/v4/spreadsheets', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${token}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      properties: {
        title,
      },
      sheets: [
        {
          properties: {
            title: 'Inventory & Valuation',
            gridProperties: {
              frozenRowCount: 1,
            },
          },
        },
      ],
    }),
  });

  if (!createRes.ok) {
    const err = await createRes.json().catch(() => ({}));
    throw new Error(err.error?.message || 'Failed to create Google Spreadsheet');
  }

  const spreadsheetData = await createRes.json();
  const spreadsheetId = spreadsheetData.spreadsheetId;
  const spreadsheetUrl = `https://docs.google.com/spreadsheets/d/${spreadsheetId}/edit`;

  // 2. Prepare headers and rows
  const headers = [
    'Asset Name',
    'Category',
    'Status',
    'Fast Cash Price ($)',
    'Max Yield Price ($)',
    'Est. Fees & Ship ($)',
    'Net In-Pocket ($)',
    'Walk-Away Floor ($)',
    'Sell-Through (%)',
    'Days to Sell',
    'Serial / VIN Stamp',
    'Condition Tier',
    'Recommended Route',
    'Single Immediate Action',
    'Date Logged',
    'Dispute-Proof Title',
  ];

  const rows = items.map((i) => [
    i.assetName,
    i.category.toUpperCase(),
    i.status.toUpperCase(),
    i.financials.fastCashPrice,
    i.financials.maxYieldPrice,
    i.financials.estimatedFeesAndShipping,
    i.financials.netInPocketYield,
    i.financials.bottomDollarWalkAwayPrice,
    i.financials.sellThroughRatePercent,
    i.financials.medianDaysToSell,
    i.identification.detectedSerialOrTags || 'UNVERIFIED',
    i.conditionReport.conditionTier,
    i.financials.recommendedRoute,
    i.singleImmediateAction,
    i.dateLogged,
    i.turnkeyListing.title,
  ]);

  // Compute summary metrics
  const totalFastCash = items.reduce((acc, curr) => acc + (curr.financials.fastCashPrice || 0), 0);
  const totalNetYield = items.reduce((acc, curr) => acc + (curr.financials.netInPocketYield || 0), 0);
  const summaryRow = [
    'TOTALS / AVERAGES',
    `${items.length} ITEMS`,
    '',
    totalFastCash,
    '',
    '',
    totalNetYield,
    '',
    '',
    '',
    '',
    '',
    '',
    'Generated by ShutterBuck Engine',
    new Date().toISOString(),
    '',
  ];

  const allValues = [headers, ...rows, summaryRow];

  // 3. Write data to sheet
  const updateRes = await fetch(
    `https://sheets.googleapis.com/v4/spreadsheets/${spreadsheetId}/values/Inventory%20%26%20Valuation!A1?valueInputOption=USER_ENTERED`,
    {
      method: 'PUT',
      headers: {
        Authorization: `Bearer ${token}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        values: allValues,
      }),
    }
  );

  if (!updateRes.ok) {
    const err = await updateRes.json().catch(() => ({}));
    throw new Error(err.error?.message || 'Failed to populate Google Sheet data');
  }

  return {
    spreadsheetId,
    spreadsheetUrl,
    title,
    rowCount: items.length,
  };
}

export async function exportVaultToGoogleSheet(
  items: AppraisalDossier[]
): Promise<SpreadsheetExportResult> {
  const token = await getAccessToken();
  if (!token) {
    throw new Error('Google authentication required. Please sign in with Google to export to Sheets.');
  }

  const title = `ShutterBuck Fortress Vault Capital Allocation (${new Date().toLocaleDateString()})`;

  // Total cash calculations
  const totalRealizedCash = items
    .filter((i) => i.status === 'sold' && i.realizedSalePrice)
    .reduce((acc, curr) => acc + (curr.realizedSalePrice || 0), 0);

  const totalUnsoldFastCash = items
    .filter((i) => i.status !== 'sold' && i.status !== 'archived')
    .reduce((acc, curr) => acc + (curr.financials.fastCashPrice || 0), 0);

  const familySafetyVault = totalRealizedCash * 0.5;
  const workingArbitrageFund = totalRealizedCash * 0.4;
  const operatorSurvival = totalRealizedCash * 0.1;

  const createRes = await fetch('https://sheets.googleapis.com/v4/spreadsheets', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${token}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      properties: { title },
      sheets: [{ properties: { title: 'Fortress Split Allocation' } }],
    }),
  });

  if (!createRes.ok) {
    throw new Error('Failed to create Fortress Vault Spreadsheet');
  }

  const spreadsheetData = await createRes.json();
  const spreadsheetId = spreadsheetData.spreadsheetId;
  const spreadsheetUrl = `https://docs.google.com/spreadsheets/d/${spreadsheetId}/edit`;

  const values = [
    ['SHUTTERBUCK // FORTRESS VAULT 50/40/10 ALLOCATION'],
    ['Generated Date', new Date().toLocaleString()],
    ['Total Physical Cash Realized', totalRealizedCash],
    ['Total Unsold Inventory Liquidity', totalUnsoldFastCash],
    [],
    ['ALLOCATION PILLAR', 'PERCENTAGE', 'CAPITAL VALUE ($)', 'MANDATE & OPERATIONAL RULE'],
    ['Family Safety Vault', '50.0%', familySafetyVault, 'Untouchable cash reserve. Stored in physical envelope/high-yield FDIC lockbox. Minimum $1,000 threshold before any speculative reinvestment.'],
    ['Working Arbitrage Fund', '40.0%', workingArbitrageFund, 'Strict 2x multiplier rule. Deployed exclusively into immediate cash flips (e-bikes, scooters, high-demand tools).'],
    ['Operator Survival Draw', '10.0%', operatorSurvival, 'Groceries, essential living overhead, transit. Zero lifestyle creep.'],
    [],
    ['ACTIVE INVENTORY PIPELINE ASSETS'],
    ['Item Name', 'Category', 'Status', 'Fast Cash ($)', 'Immediate Action'],
    ...items.map((i) => [
      i.assetName,
      i.category,
      i.status,
      i.financials.fastCashPrice,
      i.singleImmediateAction,
    ]),
  ];

  await fetch(
    `https://sheets.googleapis.com/v4/spreadsheets/${spreadsheetId}/values/Fortress%20Split%20Allocation!A1?valueInputOption=USER_ENTERED`,
    {
      method: 'PUT',
      headers: {
        Authorization: `Bearer ${token}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ values }),
    }
  );

  return {
    spreadsheetId,
    spreadsheetUrl,
    title,
    rowCount: items.length + 8,
  };
}

// ----------------------------------------------------
// GOOGLE TASKS SERVICE
// ----------------------------------------------------

export async function getOrCreateVialeTaskList(): Promise<string> {
  const token = await getAccessToken();
  if (!token) {
    throw new Error('Google authentication required. Please sign in with Google to use Tasks.');
  }

  // 1. List existing task lists
  const listRes = await fetch('https://tasks.googleapis.com/tasks/v1/users/@me/lists', {
    headers: { Authorization: `Bearer ${token}` },
  });

  if (!listRes.ok) {
    throw new Error('Failed to retrieve Google Task lists');
  }

  const listData = await listRes.json();
  const lists: GoogleTaskList[] = listData.items || [];

  const existing = lists.find(
    (l) => l.title.includes('ShutterBuck') || l.title.includes('VIALE') || l.title.includes('LEV Operations')
  );

  if (existing) {
    return existing.id;
  }

  // 2. Create if not found
  const createRes = await fetch('https://tasks.googleapis.com/tasks/v1/users/@me/lists', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${token}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      title: '⚡ ShutterBuck Operations',
    }),
  });

  if (!createRes.ok) {
    throw new Error('Failed to create ShutterBuck Operations task list in Google Tasks');
  }

  const createdList = await createRes.json();
  return createdList.id;
}

export async function fetchGoogleTasks(taskListId?: string): Promise<GoogleTaskItem[]> {
  const token = await getAccessToken();
  if (!token) {
    throw new Error('Google authentication required');
  }

  const targetListId = taskListId || (await getOrCreateVialeTaskList());
  const res = await fetch(`https://tasks.googleapis.com/tasks/v1/lists/${targetListId}/tasks?showCompleted=true&showHidden=true`, {
    headers: { Authorization: `Bearer ${token}` },
  });

  if (!res.ok) {
    throw new Error('Failed to fetch tasks from Google Tasks');
  }

  const data = await res.json();
  return (data.items || []).map((t: any) => ({
    id: t.id,
    title: t.title,
    notes: t.notes,
    status: t.status,
    due: t.due,
    completed: t.completed,
    updated: t.updated,
  }));
}

export async function createGoogleTask(
  title: string,
  notes?: string,
  due?: string,
  taskListId?: string
): Promise<GoogleTaskItem> {
  const token = await getAccessToken();
  if (!token) {
    throw new Error('Google authentication required');
  }

  const targetListId = taskListId || (await getOrCreateVialeTaskList());

  const res = await fetch(`https://tasks.googleapis.com/tasks/v1/lists/${targetListId}/tasks`, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${token}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      title,
      notes: notes || 'Dispatched from ShutterBuck Engine',
      due: due || undefined,
    }),
  });

  if (!res.ok) {
    const err = await res.json().catch(() => ({}));
    throw new Error(err.error?.message || 'Failed to create task in Google Tasks');
  }

  return await res.json();
}

export async function completeGoogleTask(
  taskId: string,
  taskListId?: string
): Promise<void> {
  const token = await getAccessToken();
  if (!token) {
    throw new Error('Google authentication required');
  }

  const targetListId = taskListId || (await getOrCreateVialeTaskList());

  const res = await fetch(
    `https://tasks.googleapis.com/tasks/v1/lists/${targetListId}/tasks/${taskId}`,
    {
      method: 'PATCH',
      headers: {
        Authorization: `Bearer ${token}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        status: 'completed',
      }),
    }
  );

  if (!res.ok) {
    throw new Error('Failed to update task status in Google Tasks');
  }
}

export async function syncRoadmapStepsToGoogleTasks(
  steps: RoadmapStep[]
): Promise<{ added: number; taskListId: string }> {
  const taskListId = await getOrCreateVialeTaskList();
  const existingTasks = await fetchGoogleTasks(taskListId);
  const existingTitles = new Set(existingTasks.map((t) => t.title.toLowerCase().trim()));

  let added = 0;
  for (const step of steps) {
    const titleKey = `[${step.levelName.toUpperCase()}] ${step.title}`.toLowerCase().trim();
    if (!existingTitles.has(titleKey)) {
      const notes = `Phase: ${step.phase} (${step.timeframe})\nTarget: ${step.targetMetric}\nFailsafe: ${step.failSafeWarning}\nVerification: ${step.verificationTrigger}`;
      await createGoogleTask(`[${step.levelName.toUpperCase()}] ${step.title}`, notes, undefined, taskListId);
      added++;
    }
  }

  return { added, taskListId };
}
